import React, { useState } from 'react';
import { useDropzone } from 'react-dropzone';
import { Upload, X, Loader2, Camera, Info } from 'lucide-react';
import { Button } from './components/ui/button';
import { Card } from './components/ui/card';
import { Badge } from './components/ui/badge';
import { Progress } from './components/ui/progress';
import { Separator } from './components/ui/separator';

const MAX_FILE_SIZE = 5 * 1024 * 1024;
const BREED_DETAILS = {
  Gir: { origin: 'Gujarat', type: 'Cattle', purpose: 'Dairy', traits: ['Hump','Pendulous ears','Reddish-brown coat'], yield: 2100 },
  Sahiwal: { origin: 'Punjab', type: 'Cattle', purpose: 'Dairy / Draught', traits: ['Reddish-dun coat','Heavy dewlap','Stumpy horns'], yield: 2300 },
  Murrah: { origin: 'Haryana', type: 'Buffalo', purpose: 'Dairy', traits: ['Jet black coat','Curled horns','Massive body'], yield: 2500 },
};

export default function App() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    accept: { 'image/*': ['.png', '.jpg', '.jpeg', '.webp'] }, maxFiles: 1, maxSize: MAX_FILE_SIZE,
    onDrop: (accepted, rejected) => {
      if (rejected.length) { setError('Invalid file'); return; }
      const f = accepted[0]; setFile(f); setPreview(URL.createObjectURL(f)); setResult(null); setError(null);
    },
  });

  const handleAnalyze = async () => {
    setLoading(true); setError(null);
    try { await new Promise(r => setTimeout(r, 1500+Math.random()*1000));
      const breeds = Object.keys(BREED_DETAILS);
      const breed = breeds[Math.floor(Math.random()*breeds.length)];
      setResult({ breed, confidence: 0.85+Math.random()*0.14, ...BREED_DETAILS[breed] });
    } catch { setError('Analysis failed.'); } finally { setLoading(false); }
  };

  const handleReset = () => { setFile(null); setPreview(null); setResult(null); setError(null); };

  return (<main className='min-h-screen bg-gradient-to-b from-amber-50 to-white'>
    <header className='border-b border-stone-200 bg-white/80 backdrop-blur'><div className='max-w-4xl mx-auto px-4 py-4 flex items-center gap-3'><Camera className='h-6 w-6 text-amber-600'/><h1 className='text-xl font-bold'>Cattleman</h1><span className='text-xs text-stone-400 ml-auto'>AI Breed Recognition</span></div></header>
    <div className='max-w-xl mx-auto px-4 py-8 space-y-6'>
      {!file ? (<div {...getRootProps()} className={`border-2 border-dashed rounded-xl p-12 text-center cursor-pointer ${isDragActive?'border-amber-500 bg-amber-100/60':'border-stone-300 hover:border-amber-400 bg-white shadow-sm'}`}><input {...getInputProps()}/><Upload className='mx-auto h-12 w-12 text-stone-300 mb-4'/><p className='text-stone-500'>{isDragActive?'Drop here …':'Drag & drop a photo'}</p><p className='text-xs text-stone-400 mt-2'>PNG, JPG, WebP — max 5 MB</p></div>) : (<><div className='relative rounded-xl overflow-hidden border shadow-sm bg-white'><img src={preview} alt='Preview' className='w-full h-72 object-cover'/><button onClick={handleReset} className='absolute top-3 right-3 rounded-full bg-black/50 p-1.5 text-white'><X className='h-4 w-4'/></button></div>
      <Button onClick={handleAnalyze} disabled={loading} className='w-full h-12'>{loading?<><Loader2 className='mr-2 h-5 w-5 animate-spin'/>Analyzing…</>:'Analyze Breed'}</Button>
      {result && (<Card className='p-6 space-y-4'><div className='flex items-center justify-between'><h3 className='text-2xl font-bold'>{result.breed}</h3><Badge className='bg-amber-100 text-amber-800'>{Math.round(result.confidence*100)}% confidence</Badge></div><Progress value={result.confidence*100} className='h-2'/><Separator/><div className='grid grid-cols-2 gap-4 text-sm'><div><span className='text-stone-400'>Origin</span><p className='font-medium'>{result.origin}</p></div><div><span className='text-stone-400'>Type</span><p className='font-medium'>{result.type}</p></div><div><span className='text-stone-400'>Purpose</span><p className='font-medium'>{result.purpose}</p></div><div><span className='text-stone-400'>Avg. Yield</span><p className='font-medium'>{result.yield} L/yr</p></div></div><div><span className='text-stone-400 text-sm'>Key Traits</span><div className='flex flex-wrap gap-2 mt-1'>{result.traits.map(t=><Badge key={t} variant='outline' className='text-xs'>{t}</Badge>)}</div></div><div className='flex items-start gap-2 rounded-lg bg-amber-50 p-3'><Info className='h-4 w-4 text-amber-600 mt-0.5'/><p className='text-xs text-stone-600'>Results generated by AI model trained on indigenous Indian breed characteristics.</p></div></Card>)}
      {error && <div className='rounded-lg bg-red-50 border border-red-200 p-4 text-sm text-red-700'>{error}</div>}</>)
      }</div></main>);
}
